#include<iostream>
using namespace std;
class student
{
    public:
    int id;
    double gpa;
   /* student(int x,double y)
    {
        x=id;
        y=gpa;
    }*/

};
int main()

     {
      student Alim;
         Alim.id = 101;
         Alim.gpa = 4.00;
         cout<<Alim.id << "   " <<showpoint<<Alim.gpa << endl;
          student Suparna;

         Suparna.id=101;
         Suparna.gpa=4.00;
         cout<<Suparna.id << "   " <<showpoint<<Suparna.gpa << endl;
         return 0;

     }
